### ISSUE TITLE
rest protocol part is not removed in RestURLStreamHandler.computeRestUrl

### ISSUE THREAD

**Issue by MarkusWb** [oxygenxml/web-author-rest-plugin#2]
There is a comment about removing it, but the rest:// part of the submitted Server URL is passed on to the REST API

**Comment by mihai-coanda** [comment]
Hello Markus,

The _rest://_ part is passed in the _url_ parameted for it to be a valid URL and will not be removed.
Starting from it you can easily compute your desired value.

Regards,
Michael
